services:
  # 应用服务
  mall-admin:
    # 用的本地镜像
    image: mall-admin:latest
    container_name: mall-admin
    ports:
      - 8080:8080
    volumes:
      - /app/mall-admin/logs:/var/logs
      - /etc/localtime:/etc/localtime
      - ./config/admin:/app/config
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CONFIG_LOCATION=file:/app/config/
    networks:
      - app_mall-net
    restart: always

  mall-portal:
    # 用的本地镜像
    image: mall-portal:latest
    container_name: mall-portal
    ports:
      - 8085:8085
    volumes:
      - /app/mall-portal/logs:/var/logs
      - /etc/localtime:/etc/localtime
      - ./config/portal:/app/config
    environment:
      - TZ=Asia/Shanghai
      - SPRING_CONFIG_LOCATION=file:/app/config/
    networks:
      - app_mall-net
    restart: always

networks:
  app_mall-net:
    external: true
