spring:
  application:
    name: mall-portal
  profiles:
    active: prod
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

server:
  port: 8085

mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml

jwt:
  tokenHeader: Authorization
  secret: mall-portal-secret
  expiration: 604800
  tokenHead: "Bearer "

secure:
  ignored:
    urls:
      - /swagger-ui/
      - /swagger-resources/**
      - /**/v2/api-docs
      - /**/*.html
      - /**/*.js
      - /**/*.css
      - /**/*.png
      - /**/*.map
      - /favicon.ico
      - /druid/**
      - /actuator/**
      - /sso/**
      - /home/**
      - /product/**
      - /brand/**
      - /alipay/**

# 自定义redis key
redis:
  database: mall
  key:
    authCode: "ums:authCode"
    orderId: "oms:orderId"
    member: "ums:member"
  expire:
    authCode: 90
    common: 86400

# 消息队列定义
rabbitmq:
  queue:
    name:
      cancelOrder: cancelOrderQueue
