spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  redis:
    host: ${REDIS_HOST}
    database: 0
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: 300ms

minio:
  endpoint: ${MINIO_ENDPOINT:https://play.min.io}
  bucketName: ${MINIO_BUCKET:mall}
  accessKey: ${MINIO_ACCESS_KEY:Q3AM3UQ867SPQQA43P2F}
  secretKey: ${MINIO_SECRET_KEY:zuf+tfteSlswRu7BJ86wekitnifILbZam1KYY3TG}

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost
  enableInnerLog: false
