server:
  port: 8085

spring:
  datasource:
    url: ${MYSQL_URL}
    username: ${MYSQL_USERNAME}
    password: ${MYSQL_PASSWORD}
    druid:
      initial-size: 5
      min-idle: 10
      max-active: 20
      web-stat-filter:
        exclusions: "*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*"
      stat-view-servlet:
        login-username: druid
        login-password: druid
  data:
    mongodb:
      uri: ${MONGODB_URI}
  redis:
    host: ${REDIS_HOST}
    database: 0
    port: ${REDIS_PORT}
    password: ${REDIS_PASSWORD}
    timeout: 300ms
  rabbitmq:
    addresses: ${RABBITMQ_URL}

logging:
  level:
    root: info
    com.macro.mall: debug

logstash:
  host: localhost
  enableInnerLog: false

alipay:
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do
  appId: your appId
  alipayPublicKey: your alipayPublicKey
  appPrivateKey: your appPrivateKey
  returnUrl: http://localhost:8060/#/pages/money/paySuccess
  notifyUrl:
